services:
  insta-reel-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: insta-reel-bot
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DB_PATH=/app/data/db.sqlite3
    volumes:
      - ./data:/app/data
      - ./proxies.json:/app/proxies.json:ro
    networks:
      - cobalt_cobalt
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

volumes:
  bot-data:
    driver: local

networks:
  cobalt_cobalt:
    external: true
